const _jobs = {};

_jobs.DEPLOY_ERC721_CONTRACT = 'DEPLOY_ERC721_CONTRACT';
_jobs.MINT_ERC721_TOKEN = 'MINT_ERC721_TOKEN';
_jobs.TRANSFER_ERC721_CONTRACT = 'TRANSFER_ERC721_CONTRACT';

module.exports = _jobs;
