const _jobs = {};

_jobs.DEPLOY_ERC721_CONTRACT = 'DEPLOY_ERC721_CONTRACT';
_jobs.MINT_ERC721_TOKEN = 'MINT_ERC721_TOKEN';
_jobs.MINT_OG_SPPORTER_TOKEN = 'MINT_OG_SPPORTER_TOKEN';

module.exports = _jobs;
